class Config:
    SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://cecilio:ceci1282@localhost/parnet_db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = '1234'

    RECAPTCHA_PUBLIC_KEY  = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
    RECAPTCHA_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
